# Generated by Django 3.2.20 on 2024-03-15 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Sarlavha')),
                ('photo', models.ImageField(upload_to='blog')),
                ('short_content', models.TextField(verbose_name='Qisqa ma`lumot')),
                ('content', models.TextField(verbose_name='Ma`lumot')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 8, 51, 118710, tzinfo=utc), verbose_name='Nashir Sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashir etilgan')], default='draft', max_length=250, verbose_name='Holati')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
