# Generated by Django 3.2.20 on 2024-03-15 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 12, 6, 680571, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
