# Generated by Django 3.2.20 on 2024-03-17 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='/blog/ccM9pdX9DDiNs05Bu5BhVAr7S2GbOafc.jpg', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 17, 12, 21, 8, 335569, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
