# Generated by Django 3.2.20 on 2024-03-18 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20240318_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 1, 52, 4, 143255, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
