# Generated by Django 3.2.20 on 2024-03-18 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 15, 2, 37, 973768, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
