# Generated by Django 3.2.20 on 2024-03-20 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blog_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 6, 31, 37, 282186, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
