# Generated by Django 3.2.20 on 2024-03-27 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20240327_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 15, 31, 6, 880050, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
