# Generated by Django 3.2.20 on 2024-04-10 03:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_blog_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_content', models.CharField(max_length=255, verbose_name="Qisqa ma'lumot")),
                ('content', models.TextField(verbose_name="To'liq ma'lumot")),
                ('photo', models.ImageField(upload_to='about_me/', verbose_name='Rasm')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 3, 40, 57, 854331, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
