# Generated by Django 3.2.20 on 2024-04-10 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20240410_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 3, 55, 9, 585295, tzinfo=utc), verbose_name='Nashir Sanasi'),
        ),
    ]
